# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e97178d649cb756663bd0998d8d1ad0091fc3f76e9618aa20afed0b1fe804de07144561f5d1c713a2ffc74dcdd8f9f853fa698627b2f3081b4ea1b15155abc8

test:
  secret_key_base: 0b5bba6ec07ac6d2e34c032a9560631de16fd307a19f56fcbd3d8c7c390c70220d6608888035364a230017c52ae329899c1d9e20398d7ec11aa61fc150d91251

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
